# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wwdc.io
email: eu@guilhermerambo.me
description: > # this means to ignore newlines until "baseurl:"
  A collection of cool tech projects related to the World Wide Developers Conference.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wwdc.io" # the base hostname & protocol for your site
twitter_username: _inside
github_username:  insidegui

# Build settings
markdown: kramdown
